### ISSUE TITLE
It would be nice if the podspec was added to the Cocoapods Specs repo

### ISSUE THREAD

**Issue by cnoon** [tuenti/TUDelorean#4]
Then we would be able to search for the pod using `pod search` and it would be more consistent with open-source pods.

**Comment by yas375** [comment]
:+1: 

In short, someone of maintainers will need to perform:

1. register in Trunk

``` sh
$ pod trunk register me@example.org 'Your Name' --description='macbook air' 
```

2. add the pod to the Trunk:

``` sh
pod trunk push TUDelorean.podspec
```

More info: [Getting setup with Trunk](http://guides.cocoapods.org/making/getting-setup-with-trunk)

**Comment by victorpimentel** [comment]
Ouch, we though we already added it to the Specs repo back in the day.

Thank you, we will add it shortly!

**Comment by cnoon** [comment]
Awesome...thanks!
